name: kayr_lang
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  video_player: ^2.6.1
  audioplayers: ^4.0.1
  http: ^0.13.6
  catcher: ^0.7.0
  animated_splash_screen: ^1.3.0
  flutter_launcher_icons: ^0.13.1
  chewie: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/img/icon.png"
  image_path_android: "assets/img/icon.png"
  
flutter:
  uses-material-design: true
  assets:
    - assets/sound/animals/
    - assets/sound/insects/
    - assets/sound/birds/
    - assets/sound/fishes/
    - assets/sound/nums/

    - assets/img/animals/
    - assets/img/insects/
    - assets/img/fishes/
    - assets/img/nums/
    - assets/img/birds/

    - assets/img/olen.jpg
    - assets/img/animals.jpg
    - assets/img/2.jpg
    - assets/img/birds.jpg
    - assets/img/seals.jpg
    - assets/img/nums.jpg
    - assets/img/video.jpg
    - assets/img/audio.jpg
    - assets/img/phone.jpg
    - assets/img/logo.png
    - assets/img/icon.png

